"""
Planner Selector

Responsible for selecting the appropriate planning algorithm
for a PLANNED node generated by decomposition.py.

Flow

User
  |
Agent
  |
Planner Selector
  |
-----------------------------
|            |              |
PlanSolve    ToT           LATS
|            |              |
|            |       Environment
|            |              |
-------------- Tool Registry
               |
           MCP Server
               |
            Database
"""

from typing import Any

from planning.lats import LATSPlanner
from planning.plan_and_solve import PlanAndSolvePlanner
from planning.schema import PlannerResult, PlannerType
from planning.tree_of_thoughts import TreeOfThoughtsPlanner


class PlannerSelector:

    def __init__(
        self,
        llm: Any,
        tool_registry: Any = None,
        environment: Any = None,
    ):

        self.llm = llm
        self.tool_registry = tool_registry
        self.environment = environment

        self.ps_planner = PlanAndSolvePlanner(
            llm,
            tool_registry,
        )

        self.tot_planner = TreeOfThoughtsPlanner(
            llm,
            tool_registry,
        )

        self.lats_planner = LATSPlanner(
            llm,
            tool_registry,
            environment,
        )

    async def select_planner(
        self,
        task: str,
    ) -> PlannerType:
        """
        Ask the LLM which planner should solve this task.

        Falls back to PLAN_AND_SOLVE if the response
        is not a valid PlannerType.
        """

        prompt = f"""
You are a planner router.

Choose exactly ONE planner.

Available planners:

- plan_and_solve
- tree_of_thoughts
- lats

Selection rules:

1. plan_and_solve
   - straightforward task
   - deterministic
   - little ambiguity

2. tree_of_thoughts
   - multiple reasonable alternatives
   - requires comparing different options

3. lats
   - requires execution
   - requires environment feedback
   - requires search through multiple actions

Task:

{task}

Return ONLY one of:

plan_and_solve
tree_of_thoughts
lats
"""

        response = await self.llm.ainvoke(prompt)

        planner_name = str(
            response.content
        ).strip().lower()

        try:
            return PlannerType(planner_name)

        except ValueError:
            # Safe fallback
            return PlannerType.PLAN_AND_SOLVE

    async def execute_planned_task(
        self,
        task: Any,
        outputs: dict[str, str],
        goal: str,
    ) -> PlannerResult:
        """
        Execute a PLANNED node using the selected planner.
        """

        context = "\n\n".join(
            f"OUTPUT FROM {dependency}:\n{outputs[dependency]}"
            for dependency in task.depends_on
        ) or "No prerequisite outputs."

        full_task_prompt = (
            f"Overall Goal:\n{goal}\n\n"
            f"Current Planned Task:\n"
            f"{task.instruction}\n\n"
            f"Context:\n{context}"
        )

        planner_type = await self.select_planner(
            full_task_prompt
        )

        planners = {
            PlannerType.PLAN_AND_SOLVE: self.ps_planner,
            PlannerType.TREE_OF_THOUGHTS: self.tot_planner,
            PlannerType.LATS: self.lats_planner,
        }

        if (
            planner_type == PlannerType.LATS
            and (
                self.tool_registry is None
                or self.environment is None
            )
        ):
            raise RuntimeError(
                "LATS requires both tool_registry "
                "and environment."
            )

        planner = planners[planner_type]

        return await planner.run(
            task.id,
            full_task_prompt,
        )
