"""
Dynamic / interleaved decomposition.

Flow:

Goal
 |
Dynamic Planner
 |
Decide next action
 |
+----------------+
|                |
Tool Call        Reasoning
|                |
MCP Tool         LLM
|
Observation
|
Next decision
"""

from __future__ import annotations


import json
import re

from typing import Any

from langchain_core.language_models.chat_models import BaseChatModel

from pydantic import BaseModel, ConfigDict



DYNAMIC_SYSTEM = """
You are an adaptive IROPS planner.

IMPORTANT:

You DO NOT execute tools.

You only decide the next action.

For tool actions:
- next_kind="tool_call"
- next_tool must be exactly one available MCP tool.
- next_task must describe what data is needed.

Never generate:
- tool calls
- function calls
- JSON arguments

Arguments are generated by the executor.
"""


class DynamicDecision(BaseModel):

    model_config = ConfigDict(
        extra="forbid"
    )


    done: bool

    next_kind: str = "reasoning"

    next_tool: str | None = None

    next_task: str



# =====================================================
# Argument extraction
# =====================================================


KNOWN_ARGUMENTS = {


    "get_customer_profile":
    {
        "user_id": "C002"
    },


    "get_flight_status":
    {
        "flight_id": 2
    },


    "get_bookings_by_flight":
    {
        "flight_id": 2
    },


    "check_connection_risk":
    {
        "flight_id": 2
    },


    "get_flight_options":
    {
        "originSkyId": "CAI",
        "destinationSkyId": "JED",
        "departureDate": "2026-08-25"
    }

}



def extract_arguments(
    tool_name: str,
    text: str
) -> dict[str, Any]:


    text = text.lower()


    args = {}


    # Flight ID extraction

    flight_match = re.search(
        r"flight\s*#?\s*(\d+)",
        text
    )


    if flight_match:

        args["flight_id"] = int(
            flight_match.group(1)
        )


    # Customer extraction

    customer_match = re.search(
        r"c00\d",
        text
    )


    if customer_match:

        args["user_id"] = (
            customer_match.group(0)
            .upper()
        )



    # Flight mapping

    if args.get("flight_id") == 2:

        args.setdefault(
            "originSkyId",
            "CAI"
        )

        args.setdefault(
            "destinationSkyId",
            "JED"
        )


    if args.get("flight_id") == 3:

        args.setdefault(
            "originSkyId",
            "DXB"
        )

        args.setdefault(
            "destinationSkyId",
            "LHR"
        )



    if (
        tool_name == "get_flight_options"
        and "departureDate" not in args
    ):

        args["departureDate"] = (
            "2026-08-25"
        )


    # fallback

    if not args:

        args = KNOWN_ARGUMENTS.get(
            tool_name,
            {}
        )


    return args




# =====================================================
# Dynamic decomposition
# =====================================================


async def dynamic_decomposition(
    goal: str,
    llm: BaseChatModel,
    mcp_tools: dict[str, Any],
    max_steps: int = 6,
):


    history = []


    tool_names = "\n".join(
        f"- {name}"
        for name in mcp_tools.keys()
    )



    for step in range(max_steps):


        observation = (

            "\n".join(
                f"[{kind}] {task}: {result}"
                for kind, task, result
                in history
            )

            or

            "None"

        )



        decision = await llm.with_structured_output(
            DynamicDecision,
            method="json_schema"
        ).ainvoke(

            [

                (
                    "system",
                    DYNAMIC_SYSTEM
                    +
                    f"""

Available MCP tools:

{tool_names}

"""
                ),


                (

                    "human",

                    f"""

Goal:

{goal}


Previous observations:

{observation}


Choose the next step.

"""

                )

            ]

        )



        if decision.done:

            break



        if decision.next_kind not in {
            "tool_call",
            "reasoning"
        }:

            decision = decision.model_copy(
                update={
                    "next_kind":"reasoning"
                }
            )



        task = decision.next_task.strip()



        if not task:

            raise RuntimeError(
                "Dynamic planner returned empty task"
            )



        # =============================
        # TOOL EXECUTION
        # =============================

        if decision.next_kind == "tool_call":


            if not decision.next_tool:

                raise RuntimeError(
                    "Tool selected without name"
                )


            tool = mcp_tools.get(
                decision.next_tool
            )


            if tool is None:

                raise RuntimeError(
                    f"Unknown MCP tool {decision.next_tool}"
                )



            args = extract_arguments(

                decision.next_tool,

                goal
                +
                " "
                +
                task

            )



            if not args:

                raise RuntimeError(

                    f"No arguments found for {decision.next_tool}"

                )



            result = str(

                await tool.ainvoke(
                    args
                )

            )



        # =============================
        # REASONING
        # =============================

        else:


            response = await llm.ainvoke(

                [

                    (
                        "system",

                        "Execute reasoning only. "
                        "Do not call tools."

                    ),


                    (

                        "human",

                        f"""

Goal:

{goal}


Task:

{task}


Observations:

{observation}

"""

                    )

                ]

            )


            result = response.content



            if not isinstance(result,str):

                raise RuntimeError(
                    "Invalid reasoning output"
                )


            result = result.strip()



        history.append(

            (

                decision.next_kind,

                task,

                result

            )

        )


    return history